# Generated by Django 4.0.3 on 2022-03-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmenu', '0002_alter_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
